apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rekrutteringsbistand-stillingssok-proxy
  namespace: toi
  labels:
    team: toi
spec:
  groups:
    - name: rekrutteringsbistand-stillingssok-proxy
      rules:
        - alert: rekrutteringsbistand-stillingssok-proxy
          expr: kube_deployment_status_replicas_available{deployment="rekrutteringsbistand-stillingssok-proxy"} == 0
          for: 1s
          annotations:
            summary: Appen er nede
            action: "https://logs.adeo.no/app/r/s/5DXEM"
          labels:
            namespace: toi
            severity: critical

        - alert: rekrutteringsbistand-stillingssok-proxy
          expr: sum(increase(log_messages_errors{app="rekrutteringsbistand-stillingssok-proxy", level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Appen har logget en error
            action: "https://logs.adeo.no/app/r/s/5DXEM"
          labels:
            namespace: toi
            severity: critical

        - alert: rekrutteringsbistand-stillingssok-proxy
          expr: sum(increase(log_messages_errors{app="rekrutteringsbistand-stillingssok-proxy", level="Warning"}[10m])) > 3
          for: 1s
          annotations:
            summary: Økning i warnings
            action: "https://logs.adeo.no/app/r/s/5DXEM"
          labels:
            namespace: toi
            severity: warning
