apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: rekrutteringsbistand-stillingssok-proxy
  namespace: toi
  labels:
    team: toi
spec:
  image: {{image}}
  port: 8300
  ingresses:
  {{#each ingress as |url|}}
      - {{url}}
  {{/each}}
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  replicas:
    min: {{min_replicas}}
    max: {{max_replicas}}
  resources:
    requests:
      cpu: {{requested_cpu}}
      memory: 512Mi
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - NAVident
        groups:
          - id: {{adGruppeModiaGenerellTilgang}}
          - id: {{adGruppeJobbsøkerrettet}}
          - id: {{adGruppeArbeidsgiverrettet}}
          - id: {{adGruppeUtvikler}}
  accessPolicy:
    inbound:
      rules:
        - application: foresporsel-om-deling-av-cv-api
          namespace: toi
          cluster: {{fss-cluster}}
        - application: rekrutteringsbistand
        - application: rekrutteringsbistand-frontend
  openSearch:
    access: read
    instance: rekrutteringsbistand-stilling
