apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: rekrutteringsbistand-stillingssok-proxy
  namespace: toi
  labels:
    team: toi
spec:
  image: {{image}}
  port: 8300
  ingresses:
  {{#each ingress as |url|}}
      - {{url}}
  {{/each}}
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  azure:
    application:
      enabled: true
      claims:
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: rekrutteringsbistand-statistikk-api
          namespace: toi
          cluster: {{fss-cluster}}
        - application: foresporsel-om-deling-av-cv-api
          namespace: arbeidsgiver-inkludering
          cluster: {{fss-cluster}}
        - application: rekrutteringsbistand-stillingssok
          namespace: toi
        - application: rekrutteringsbistand-container
          namespace: toi
  openSearch:
    access: read
    instance: rekrutteringsbistand-stilling
