name: Build and deploy
on: [ push, workflow_dispatch ]

jobs:
  call-build-and-deploy:
    uses: navikt/toi-github-actions-workflows/.github/workflows/build-and-deploy.yaml@v17
    with:
      java-version: '25'
      deploy-to-dev-if-branch-name-is: 'autobump-docker-baseimage'
      baseimage-tagged-ref: 'europe-north1-docker.pkg.dev/cgr-nav/pull-through/nav.no/jre:openjdk-25'
    permissions:
      contents: read
      id-token: write
      security-events: write
    secrets: inherit
