name: Oppdater Docker run-time base-image
on:
  schedule:
    - cron: '29 5 * * 1'
  workflow_dispatch:

jobs:
  call-oppdater-docker-baseimage:
    uses: navikt/toi-github-actions-workflows/.github/workflows/oppdater-docker-baseimage.yaml@v17
    with:
      deploy-workflow-filnavn: deploy.yml
    permissions:
      id-token: write
      actions: write
